insert into wine_categoria(id_categoria, nombre, descripcion) values(1,'Agliánico','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(2,'Albariño','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(3,'Ancellotta','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(4,'Barbera','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(5,'Bequignol','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(6,'Blanco','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(7,'Blend','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(8,'Bonarda','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(9,'Cabernet Franc','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(10,'Cabernet Sauvignon','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(11,'Canarí','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(12,'Carignan','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(13,'Carmenere','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(14,'Cereza','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(15,'Chardonnay','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(16,'Chenin','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(17,'Cinsault','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(18,'Cordisco','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(19,'Criolla','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(20,'Fiano','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(21,'Garnacha','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(22,'Gewurztraminer','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(23,'Glera','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(24,'Gruner Veltliner','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(25,'Jerez','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(26,'Lambrusco','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(27,'Malbec','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(28,'Malvasia','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(29,'Marsala','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(30,'Marsanne','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(31,'Marselan','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(32,'Mencía','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(33,'Merlot','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(34,'Monastrell','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(35,'Montepulciano','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(36,'Moscatel','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(37,'Moscato Giallo','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(38,'Mourvedre','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(39,'Nebbiolo','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(40,'Nerello Mascalese','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(41,'Nero D''Avola','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(42,'Oporto','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(43,'Pedro Ximénez','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(44,'Petit Manseg','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(45,'Petit Verdot','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(46,'Pinot Grigio','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(47,'Pinot Gris','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(48,'Pinot Noir','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(49,'Porto','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(50,'Rosado','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(51,'Rosé','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(52,'Riesling','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(53,'Sangiovese','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(54,'Sauvignon Blanc','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(55,'Semillón','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(56,'Syrah','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(57,'Tannat','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(58,'Tempranillo','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(59,'Teroldego','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(60,'Tinto','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(61,'Tocai Friulano','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(62,'Torrontés','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(63,'Trousseau','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(64,'Verdejo','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(65,'Viognier','--TEXT--');
insert into wine_categoria(id_categoria, nombre, descripcion) values(66,'Zinfandel','--TEXT--');
