insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(1,'Agliánico','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(3,'Ancellotta','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(4,'Barbera','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(8,'Bonarda','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(9,'Cabernet Franc','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(10,'Cabernet Sauvignon','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(11,'Canarí','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(12,'Carignan','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(13,'Carmenere','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(17,'Cinsault','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(21,'Garnacha','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(25,'Jerez','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(26,'Lambrusco','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(27,'Malbec','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(29,'Marsala','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(31,'Marselan','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(32,'Mencía','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(33,'Merlot','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(34,'Monastrell','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(35,'Montepulciano','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(38,'Mourvedre','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(39,'Nebbiolo','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(40,'Nerello Mascalese','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(41,'Nero D''Avola','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(42,'Oporto','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(45,'Petit Verdot','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(48,'Pinot Noir','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(49,'Porto','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(50,'Rosado','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(51,'Rosé','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(53,'Sangiovese','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(56,'Syrah','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(57,'Tannat','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(58,'Tempranillo','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(59,'Teroldego','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(60,'Tinto','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(63,'Trousseau','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(66,'Zinfandel','--TEXT--','tinto');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(2,'Albariño','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(6,'Blanco','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(15,'Chardonnay','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(16,'Chenin','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(22,'Gewurztraminer','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(36,'Moscatel','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(47,'Pinot Gris','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(52,'Riesling','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(54,'Sauvignon Blanc','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(55,'Semillón','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(65,'Viognier','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(5,'Bequignol','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(7,'Blend','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(14,'Cereza','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(18,'Cordisco','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(19,'Criolla','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(20,'Fiano','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(23,'Glera','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(24,'Gruner Veltliner','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(28,'Malvasia','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(30,'Marsanne','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(37,'Moscato Giallo','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(43,'Pedro Ximénez','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(44,'Petit Manseg','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(46,'Pinot Grigio','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(61,'Tocai Friulano','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(62,'Torrontés','--TEXT--','blanco');
insert into wine_categoria(id_categoria, nombre, descripcion,agrupado) values(64,'Verdejo','--TEXT--','blanco');
