# Generated by Django 3.2.18 on 2023-05-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_alter_contacto_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wine.producto')),
            ],
        ),
    ]
