# Generated by Django 3.2.18 on 2023-06-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='img_default.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
