# Generated by Django 3.2.18 on 2023-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_auto_20230618_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='img_default.png', max_length=50),
        ),
    ]
