# Generated by Django 3.2.18 on 2023-05-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bodega',
            field=models.CharField(default='', max_length=50),
        ),
    ]
