# Generated by Django 3.2.18 on 2023-05-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_producto_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='bodega',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
