# Generated by Django 3.2.18 on 2023-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20230508_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('contacto', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('telefono', models.CharField(max_length=100)),
                ('consulta', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True)),
            ],
        ),
    ]
